// Code generated by hydra. DO NOT EDIT.
// CLI command structs generated from the API definition

use clap::{Args, Subcommand};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Subcommand)]
pub enum GeneratedCommand {
    /// List records with an explicit presentation flag.
    ListRecords(ListRecordsArgs),
    /// Read status without request parameters.
    Status(StatusArgs),
    /// Stream events over HTTP and CLI only.
    Watch(WatchArgs),
}

impl GeneratedCommand {
    pub const fn operation_name(&self) -> &'static str {
        match self {
            Self::ListRecords(_) => "list_records",
            Self::Status(_) => "status",
            Self::Watch(_) => "subscribe_events",
        }
    }

    pub fn parameters_json(&self) -> serde_json::Value {
        match self {
            Self::ListRecords(args) => serde_json::json!({"cursor": args.cursor.clone(), "query": args.query.clone(), "label": args.label.clone()}),
            Self::Status(_args) => serde_json::json!({}),
            Self::Watch(args) => serde_json::json!({"cursor": args.cursor.clone()}),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Args)]
pub struct ListRecordsArgs {
    /// Opaque query cursor.
    #[arg(long)]
    pub cursor: Option<String>,
    /// Optional query text.
    #[arg(long)]
    pub query: Option<String>,
    /// Optional CLI-only labels for the query.
    #[arg(long = "label", action = clap::ArgAction::Append)]
    pub label: Option<Vec<String>>,
    /// Include the checkpoint alongside each displayed record.
    #[arg(long = "include-cursor", action = clap::ArgAction::SetTrue)]
    pub include_cursor: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Args)]
pub struct StatusArgs {
    /// Include verbose status presentation details.
    #[arg(long = "verbose", action = clap::ArgAction::SetTrue)]
    pub verbose: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Args)]
pub struct WatchArgs {
    /// Opaque replay cursor.
    #[arg(long)]
    pub cursor: Option<String>,
    /// Include the checkpoint alongside each streamed event.
    #[arg(long = "include-cursor", action = clap::ArgAction::SetTrue)]
    pub include_cursor: bool,
}

