// Code generated by hydra. DO NOT EDIT.
// HTTP route handlers generated from the API definition

use std::collections::BTreeMap;

use axum::{extract::{State, Query}, response::Response, routing::{get}, Router};
use serde_json::Value;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GeneratedRoute {
    pub name: &'static str,
    pub method: &'static str,
    pub path: &'static str,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GeneratedOperationInput {
    pub path: BTreeMap<String, String>,
    pub query: BTreeMap<String, String>,
    pub body: Value,
}

pub const GENERATED_ROUTES: &[GeneratedRoute] = &[
    GeneratedRoute { name: "read_events", method: "GET", path: "/events" },
];

pub fn generated_router() -> Router<crate::HttpErrorFixtureState> {
    Router::new()
        .route("/events", get(read_events))
}

/// Streaming (SSE) operations declared in the API definition. The
/// generated surface exposes only this metadata plus the binding hooks
/// below; the handwritten server supplies the handler.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GeneratedSseRoute {
    pub name: &'static str,
    pub method: &'static str,
    pub path: &'static str,
}

pub const GENERATED_SSE_ROUTES: &[GeneratedSseRoute] = &[
    GeneratedSseRoute { name: "subscribe_events", method: "GET", path: "/events/stream" },
];

/// Runtime binding hook for the `subscribe_events` SSE operation. The handwritten server implements this
/// binding; generated code does not generate a duplicate route.
pub fn bind_subscribe_events(router: Router<crate::HttpErrorFixtureState>) -> Router<crate::HttpErrorFixtureState> {
    crate::bind_runtime_sse_subscribe_events(router)
}

/// Typed HTTP error responses declared for the `read_events` operation.
pub mod read_events_http_errors {
    use axum::{
        http::StatusCode,
        response::{IntoResponse, Response},
        Json,
    };
    use serde::Serialize;

    #[derive(Serialize)]
    struct RateLimitedBody {
        error: String,
        retry_after: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        retry_hint: Option<String>,
    }

    /// Typed HTTP response for the declared `rate_limited` error.
    pub struct RateLimitedResponse {
        body: RateLimitedBody,
    }

    impl IntoResponse for RateLimitedResponse {
        fn into_response(self) -> Response {
            (StatusCode::from_u16(429).expect("validated HTTP error status"), Json(self.body)).into_response()
        }
    }

    /// Construct the declared 429 `rate_limited` HTTP response.
    pub fn rate_limited(retry_after: String, retry_hint: Option<String>) -> RateLimitedResponse {
        RateLimitedResponse {
            body: RateLimitedBody {
                error: "rate \u{1} \"limited\"".to_owned(),
                retry_after,
                retry_hint,
            },
        }
    }

}

/// Typed HTTP error responses declared for the `subscribe_events` operation.
pub mod subscribe_events_http_errors {
    use axum::{
        http::StatusCode,
        response::{IntoResponse, Response},
        Json,
    };
    use serde::Serialize;

    #[derive(Serialize)]
    struct InvalidReplayCursorBody {
        error: String,
    }

    /// Typed HTTP response for the declared `invalid_replay_cursor` error.
    pub struct InvalidReplayCursorResponse {
        body: InvalidReplayCursorBody,
    }

    impl IntoResponse for InvalidReplayCursorResponse {
        fn into_response(self) -> Response {
            (StatusCode::from_u16(400).expect("validated HTTP error status"), Json(self.body)).into_response()
        }
    }

    /// Construct the declared 400 `invalid_replay_cursor` HTTP response.
    pub fn invalid_replay_cursor() -> InvalidReplayCursorResponse {
        InvalidReplayCursorResponse {
            body: InvalidReplayCursorBody {
                error: "invalid_replay_cursor".to_owned(),
            },
        }
    }

    #[derive(Serialize)]
    struct ReplayCursorExpiredBody {
        error: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        oldest_cursor: Option<String>,
    }

    /// Typed HTTP response for the declared `replay_cursor_expired` error.
    pub struct ReplayCursorExpiredResponse {
        body: ReplayCursorExpiredBody,
    }

    impl IntoResponse for ReplayCursorExpiredResponse {
        fn into_response(self) -> Response {
            (StatusCode::from_u16(409).expect("validated HTTP error status"), Json(self.body)).into_response()
        }
    }

    /// Construct the declared 409 `replay_cursor_expired` HTTP response.
    pub fn replay_cursor_expired(oldest_cursor: Option<String>) -> ReplayCursorExpiredResponse {
        ReplayCursorExpiredResponse {
            body: ReplayCursorExpiredBody {
                error: "replay_cursor_expired".to_owned(),
                oldest_cursor,
            },
        }
    }

    #[derive(Serialize)]
    struct StreamUnavailableBody {
        error: String,
    }

    /// Typed HTTP response for the declared `stream_unavailable` error.
    pub struct StreamUnavailableResponse {
        body: StreamUnavailableBody,
    }

    impl IntoResponse for StreamUnavailableResponse {
        fn into_response(self) -> Response {
            (StatusCode::from_u16(503).expect("validated HTTP error status"), Json(self.body)).into_response()
        }
    }

    /// Construct the declared 503 `stream_unavailable` HTTP response.
    pub fn stream_unavailable() -> StreamUnavailableResponse {
        StreamUnavailableResponse {
            body: StreamUnavailableBody {
                error: "stream_unavailable".to_owned(),
            },
        }
    }

}

async fn read_events(
    State(state): State<crate::HttpErrorFixtureState>,
    Query(query): Query<BTreeMap<String, String>>,
) -> Response {
    crate::http_error_fixture_dispatch(
        &state,
        "read_events",
        GeneratedOperationInput {
            path: BTreeMap::new(),
            query,
            body: Value::Null,
        },
    )
    .await
}
